# Simplified build workflow for custom packages
# Builds only .deb package
# Triggered manually only for my-build branch

name: Build .deb package
on:
  push:
    branches:
      - my-build
permissions: {}
jobs:
  build-deb-x86:
    name: Build Linux .deb amd64
    runs-on: ubuntu-22.04
    container: ubuntu:20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up base dependencies
        run: |
          set -eu
          apt-get -qq update
          apt-get install -y software-properties-common sudo curl
          add-apt-repository ppa:git-core/ppa
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt-get -qq update
          apt-get -qq -y install git-core gh
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Set up build dependencies
        run: ./.github/autobuild/linux_deb.sh setup
        env:
          JAMULUS_BUILD_VERSION: "3.11.0dev"

      - name: Build .deb package
        run: ./.github/autobuild/linux_deb.sh build
        env:
          JAMULUS_BUILD_VERSION: "3.11.0dev"


      - name: Get artifacts
        id: get-artifacts
        run: ./.github/autobuild/linux_deb.sh get-artifacts
        env:
          JAMULUS_BUILD_VERSION: "3.11.0dev"

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: jamulus-deb
          path: deploy/jamulus_*.deb
          retention-days: 31
          if-no-files-found: error
