# Simplified build workflow for custom packages
# Builds only .exe and .apk packages
# Triggered manually only for my-build branch

name: Build .exe, .apk and macOS packages
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    if: github.ref == 'refs/heads/my-build'
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows .exe
            os: windows-2022
            command: powershell .\.github\autobuild\windows.ps1 -Stage
            target: windows

          - name: Android .apk
            os: ubuntu-22.04
            command: ./.github/autobuild/android.sh
            target: android
            fetch_depth: 0

          - name: macOS package
            os: macos-14
            command: QT_VERSION=6.8.1 SIGN_IF_POSSIBLE=1 TARGET_ARCHS="x86_64 arm64" ./.github/autobuild/mac.sh
            target: macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: ${{ matrix.config.target == 'android' }}
          fetch-depth: ${{ matrix.config.fetch_depth || '1' }}

      - name: Cache Windows dependencies
        if: matrix.config.target == 'windows'
        uses: actions/cache@v4
        with:
          path: |
            C:\Qt
            C:\ChocoCache
            C:\AutobuildCache
          key: windows-${{ hashFiles('.github/workflows/autobuild.yml') }}

      - name: Cache Android dependencies
        if: matrix.config.target == 'android'
        uses: actions/cache@v4
        with:
          path: |
            /opt/Qt
            /opt/android/android-sdk
            /opt/android/android-ndk
          key: android-${{ hashFiles('.github/workflows/autobuild.yml') }}

      - name: Cache macOS dependencies
        if: matrix.config.target == 'macos'
        uses: actions/cache@v4
        with:
          path: |
            /opt/qt
            ~/Library/Cache/jamulus-homebrew-bottles
          key: macos-${{ hashFiles('.github/workflows/autobuild.yml') }}

      - name: Set up build dependencies
        run: ${{ matrix.config.command }} setup
        env:
          JAMULUS_BUILD_VERSION: 3.11.0

      - name: Build
        run: ${{ matrix.config.command }} build
        env:
          JAMULUS_BUILD_VERSION: 3.11.0

      - name: Get artifacts
        id: get-artifacts
        run: ${{ matrix.config.command }} get-artifacts
        env:
          JAMULUS_BUILD_VERSION: 3.11.0

      - name: Upload primary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-artifacts.outputs.artifact_1 }}
          path: deploy/${{ steps.get-artifacts.outputs.artifact_1 }}
          retention-days: 31
          if-no-files-found: error

      - name: Upload secondary artifact
        if: steps.get-artifacts.outputs.artifact_2
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-artifacts.outputs.artifact_2 }}
          path: deploy/${{ steps.get-artifacts.outputs.artifact_2 }}
          retention-days: 31
          if-no-files-found: error
